"""create security features

Revision ID: ff25e33ffc73
Revises: 72c0d5191db3
Create Date: 2025-08-25 19:49:27.349191

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff25e33ffc73'
down_revision: Union[str, Sequence[str], None] = '72c0d5191db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pages_owner_id'), 'pages', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_owner_id'), table_name='pages')
    # ### end Alembic commands ###
